In [16]:
import pandas as pd

In [17]:
perception_df = pd.read_csv('Perceptions_CJS_England and Wales_2024Q4.csv')

perception_df

,Year,Quarter,MeasurementVar,MeasurementLevel,MeasurementType,Geography,HouseholdType,Sex,Age,CharacteristicVar,Characteristic,Estimate,StandardError,UnweightedCount
0,2024,4,catt2,Person,Perception,England and Wales,,All people,16-24,accharm3,Detached house,49.81129436,3.989754607,229
1,2024,4,catt2,Person,Perception,England and Wales,,All people,16-24,accharm3,Flats/maisonettes,45.58845912,3.317115821,460
2,2024,4,catt2,Person,Perception,England and Wales,,All people,16-24,accharm3,House,51.5229105,1.880560431,1194
3,2024,4,catt2,Person,Perception,England and Wales,,All people,16-24,accharm3,Other accommodation,[x],[x],[x]
4,2024,4,catt2,Person,Perception,England and Wales,,All people,16-24,accharm3,Semi-detached house,52.39973521,3.208098498,418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28504,2024,4,ratpol3,Person,Perception,England and Wales,,Male,75+,tothhin4,No income stated or not enough information pro...,46.32457436,10.80623579,30
28505,2024,4,ratpol3,Person,Perception,England and Wales,,Male,75+,tothhin4,"Up to 10,399",57.52315873,5.778454354,124
28506,2024,4,ratpol3,Person,Perception,England and Wales,,Male,75+,weekday2,3-7 hours,44.52548884,2.640605891,497
28507,2024,4,ratpol3,Person,Perception,England and Wales,,Male,75+,weekday2,7 plus hrs,44.15598861,7.489123729,62
28508,2024,4,ratpol3,Person,Perception,England and Wales,,Male,75+,weekday2,Less than 3 hrs,49.72251202,1.5922449,1543

In [18]:
perception_df['MeasurementVar'].unique()

array(['catt2', 'catt2a', 'catt2b', 'cjsovb1dv', 'fairova1dv', 'patt1',
       'patt2', 'patt3', 'patt5', 'patt6', 'patt6b', 'patt7', 'ratpol3'],
      dtype=object)

In [19]:
perception_df['MeasurementType'].unique()

array(['Perception'], dtype=object)

In [20]:
percept2_df = pd.read_csv('Perceptions_Other_England and Wales_2024Q4.csv')

In [21]:
percept2_df['MeasurementVar'].unique()

array(['abancar1', 'bvpiburg', 'bvpicar', 'bvpifrd', 'bvpiviol',
       'clcntry2', 'clloc2', 'drug1', 'drunk1', 'nasb7hi', 'noisneg1',
       'rubb1', 'teen1', 'vandals1'], dtype=object)

In [22]:
ref_data = pd.read_csv("reference-measurementvar-with-categories.csv")

In [23]:
merge2_df = pd.merge(percept2_df, ref_data, how='left', left_on='MeasurementVar', right_on='MeasurementVar')

In [24]:
merge2_df

,Year,Quarter,MeasurementVar,MeasurementLevel_x,MeasurementType_x,Geography,HouseholdType,Sex,Age,CharacteristicVar,Characteristic,Estimate,StandardError,UnweightedCount,MeasurementLabel,MeasurementLevel_y,MeasurementType_y,CrimeCategory
0,2024,4,abancar1,Person,Perception,England and Wales,,All people,16-24,accharm3,Detached house,2.329221622,2.304047581,54,Perceived problem with abandoned or burnt out ...,Person,Perception,anti-social-behaviour
1,2024,4,abancar1,Person,Perception,England and Wales,,All people,16-24,accharm3,Flats/maisonettes,2.594202177,1.877507993,109,Perceived problem with abandoned or burnt out ...,Person,Perception,anti-social-behaviour
2,2024,4,abancar1,Person,Perception,England and Wales,,All people,16-24,accharm3,House,2.550872104,0.985034707,287,Perceived problem with abandoned or burnt out ...,Person,Perception,anti-social-behaviour
3,2024,4,abancar1,Person,Perception,England and Wales,,All people,16-24,accharm3,Other accommodation,[x],[x],[x],Perceived problem with abandoned or burnt out ...,Person,Perception,anti-social-behaviour
4,2024,4,abancar1,Person,Perception,England and Wales,,All people,16-24,accharm3,Semi-detached house,2.543722456,1.626887078,95,Perceived problem with abandoned or burnt out ...,Person,Perception,anti-social-behaviour
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30697,2024,4,vandals1,Person,Perception,England and Wales,,Male,75+,tothhin4,No income stated or not enough information pro...,[x],[x],[x],Perceived problem with vandalism and graffiti ...,Person,Perception,criminal-damage-arson
30698,2024,4,vandals1,Person,Perception,England and Wales,,Male,75+,tothhin4,"Up to 10,399",5.885042489,5.670725791,37,Perceived problem with vandalism and graffiti ...,Person,Perception,criminal-damage-arson
30699,2024,4,vandals1,Person,Perception,England and Wales,,Male,75+,weekday2,3-7 hours,5.139049679,2.286693271,130,Perceived problem with vandalism and graffiti ...,Person,Perception,criminal-damage-arson
30700,2024,4,vandals1,Person,Perception,England and Wales,,Male,75+,weekday2,7 plus hrs,1.649978888,1.704261945,15,Perceived problem with vandalism and graffiti ...,Person,Perception,criminal-damage-arson
30701,2024,4,vandals1,Person,Perception,England and Wales,,Male,75+,weekday2,Less than 3 hrs,6.036529561,1.346306957,440,Perceived problem with vandalism and graffiti ...,Person,Perception,criminal-damage-arson

In [25]:
duplicates = merge2_df[merge2_df.duplicated()]
duplicates_count = duplicates.shape[0]
print(f"Number of duplicate rows: {duplicates_count}")

Number of duplicate rows: 0

In [26]:
merge2_df.columns

Index(['Year', 'Quarter', 'MeasurementVar', 'MeasurementLevel_x',
       'MeasurementType_x', 'Geography', 'HouseholdType', 'Sex', 'Age',
       'CharacteristicVar', 'Characteristic', 'Estimate', 'StandardError',
       'UnweightedCount', 'MeasurementLabel', 'MeasurementLevel_y',
       'MeasurementType_y', 'CrimeCategory'],
      dtype='object')

In [27]:
merge2_df['MeasurementLevel_x'].unique()

array(['Person'], dtype=object)

In [28]:
merge2_df = merge2_df.drop(columns=['MeasurementVar', 'MeasurementType_x', 'MeasurementLevel_x', 'MeasurementLevel_y', 'MeasurementType_y',
                                     'Sex', 'HouseholdType', 'Quarter', 'Geography'])
merge2_df.head()

,Year,Age,CharacteristicVar,Characteristic,Estimate,StandardError,UnweightedCount,MeasurementLabel,CrimeCategory
0,2024,16-24,accharm3,Detached house,2.329221622,2.304047581,54,Perceived problem with abandoned or burnt out ...,anti-social-behaviour
1,2024,16-24,accharm3,Flats/maisonettes,2.594202177,1.877507993,109,Perceived problem with abandoned or burnt out ...,anti-social-behaviour
2,2024,16-24,accharm3,House,2.550872104,0.985034707,287,Perceived problem with abandoned or burnt out ...,anti-social-behaviour
3,2024,16-24,accharm3,Other accommodation,[x],[x],[x],Perceived problem with abandoned or burnt out ...,anti-social-behaviour
4,2024,16-24,accharm3,Semi-detached house,2.543722456,1.626887078,95,Perceived problem with abandoned or burnt out ...,anti-social-behaviour

The estimate is shown as a percentage

In [29]:
merge2_df = merge2_df[(merge2_df['Characteristic'] == 'Yorkshire and The Humber')]
merge2_df.head()

,Year,Age,CharacteristicVar,Characteristic,Estimate,StandardError,UnweightedCount,MeasurementLabel,CrimeCategory
28,2024,16-24,gor,Yorkshire and The Humber,0.252152131,0.253896624,43,Perceived problem with abandoned or burnt out ...,anti-social-behaviour
126,2024,16+,gor,Yorkshire and The Humber,2.461599667,0.903643195,854,Perceived problem with abandoned or burnt out ...,anti-social-behaviour
218,2024,25-34,gor,Yorkshire and The Humber,0.802493714,0.585618701,109,Perceived problem with abandoned or burnt out ...,anti-social-behaviour
309,2024,35-44,gor,Yorkshire and The Humber,4.517668618,2.515850761,149,Perceived problem with abandoned or burnt out ...,anti-social-behaviour
401,2024,45-54,gor,Yorkshire and The Humber,5.317954363,3.180712982,121,Perceived problem with abandoned or burnt out ...,anti-social-behaviour

In [30]:
# Round estimate to 2 decimal places and show as percentage
# The value shown is already calculated as a percentage, so we just need to format it
merge2_df['Estimate'] = merge2_df['Estimate'].astype(float)  # Ensure it's float before rounding
# Round to 2 decimal places and convert to string with percentage sign
merge2_df['Estimate'] = merge2_df['Estimate'].round(2)  
merge2_df['Estimate'] = merge2_df['Estimate'].astype(str) + '%'

In [31]:
merge2_df

,Year,Age,CharacteristicVar,Characteristic,Estimate,StandardError,UnweightedCount,MeasurementLabel,CrimeCategory
28,2024,16-24,gor,Yorkshire and The Humber,0.25%,0.253896624,43,Perceived problem with abandoned or burnt out ...,anti-social-behaviour
126,2024,16+,gor,Yorkshire and The Humber,2.46%,0.903643195,854,Perceived problem with abandoned or burnt out ...,anti-social-behaviour
218,2024,25-34,gor,Yorkshire and The Humber,0.8%,0.585618701,109,Perceived problem with abandoned or burnt out ...,anti-social-behaviour
309,2024,35-44,gor,Yorkshire and The Humber,4.52%,2.515850761,149,Perceived problem with abandoned or burnt out ...,anti-social-behaviour
401,2024,45-54,gor,Yorkshire and The Humber,5.32%,3.180712982,121,Perceived problem with abandoned or burnt out ...,anti-social-behaviour
...,...,...,...,...,...,...,...,...,...
30277,2024,35-44,gor,Yorkshire and The Humber,21.95%,7.58565109,60,Perceived problem with vandalism and graffiti ...,criminal-damage-arson
30368,2024,45-54,gor,Yorkshire and The Humber,12.68%,4.467736787,56,Perceived problem with vandalism and graffiti ...,criminal-damage-arson
30459,2024,55-64,gor,Yorkshire and The Humber,5.21%,3.091557551,73,Perceived problem with vandalism and graffiti ...,criminal-damage-arson
30550,2024,65-74,gor,Yorkshire and The Humber,4.89%,2.070460162,70,Perceived problem with vandalism and graffiti ...,criminal-damage-arson
30640,2024,75+,gor,Yorkshire and The Humber,0.88%,0.661211895,74,Perceived problem with vandalism and graffiti ...,criminal-damage-arson

In [33]:
merge2_df = merge2_df.drop(columns=['CharacteristicVar', 'StandardError', 'UnweightedCount'])

In [34]:
merge2_df.head()

,Year,Age,Characteristic,Estimate,MeasurementLabel,CrimeCategory
28,2024,16-24,Yorkshire and The Humber,0.25%,Perceived problem with abandoned or burnt out ...,anti-social-behaviour
126,2024,16+,Yorkshire and The Humber,2.46%,Perceived problem with abandoned or burnt out ...,anti-social-behaviour
218,2024,25-34,Yorkshire and The Humber,0.8%,Perceived problem with abandoned or burnt out ...,anti-social-behaviour
309,2024,35-44,Yorkshire and The Humber,4.52%,Perceived problem with abandoned or burnt out ...,anti-social-behaviour
401,2024,45-54,Yorkshire and The Humber,5.32%,Perceived problem with abandoned or burnt out ...,anti-social-behaviour

In [35]:
# Save the final DataFrame to a CSV file
merge2_df.to_csv('Perceptions_Data_Yorkshire.csv', index=False) 
# Read the saved CSV file to verify
saved_df = pd.read_csv('Perceptions_Data_Yorkshire.csv')